"""AMD Vivado cross-verification adapter (optional EDA layer, Windows host).

Implements the vendor-neutral EDA contract (prepare / execute /
collect_artifacts / parse_results / normalize_evidence / calculate_hashes /
report_status) for Vivado batch synthesis. Runs on the Windows Vivado
install; Linux CI records UNAVAILABLE (documented, never silent).

The user contract for this adapter: every limitation prints to the console
as it is hit, WITH the alternative, so no Vivado result is ever mistaken
for more than it is. See note().
"""
from __future__ import annotations

import hashlib
import json
import os
import re
import subprocess
import time
from dataclasses import dataclass, field

VIVADO_BAT = r"C:\AMDDesignTools\2026.1\Vivado\bin\vivado.bat"
PART = "xc7a100tcsg324-1"  # Arty A7-100T class (demo has no board constraints)
SYNTH_TIMEOUT_S = 1500


def note(limitation: str, alternative: str) -> str:
    """Print a limitation + its alternative. Returns the formatted line so
    callers can also record it in evidence."""
    line = (f"[vivado-adapter] LIMITATION: {limitation} "
            f"| alternative: {alternative}")
    print(line, flush=True)
    return line


@dataclass
class VivadoRun:
    tool: str = "vivado"
    tool_version: str = ""
    target_device: str = PART
    rtl_commit: str = ""
    run_id: str = ""
    requirement_ids: tuple = ()
    status: str = "NOT_EXECUTED"  # PASS/FAIL/UNAVAILABLE/NOT_EXECUTED/...
    checks: dict = field(default_factory=dict)  # synth/drc/timing/util
    artifacts: list = field(default_factory=list)
    artifact_hashes: dict = field(default_factory=dict)
    limitations: list = field(default_factory=list)
    log_excerpt: str = ""
    duration_s: float = 0.0
    reason: str = ""


TCL_TEMPLATE = """# Generated by vivado_adapter.py — in-memory batch synth per block.
set PART "{part}"
{blocks}
exit
"""

BLOCK_TCL = """
# --- {top} ---
create_project -in_memory -part $PART
read_verilog "{src}"
read_xdc "{xdc}"
synth_design -top {top} -flatten_hierarchy rebuilt
opt_design
place_design
route_design
report_timing_summary -file "{out}/timing.rpt" -max_paths 5
report_utilization -file "{out}/util.rpt"
report_drc -file "{out}/drc.rpt"
write_checkpoint -force "{out}/post_route.dcp"
close_project
"""


def write_batch_tcl(blocks: list[dict], tcl_path: str,
                    part: str = PART, xdc: str = "") -> str:
    """blocks: [{top, src, outdir}]. Returns tcl_path. Paths are written
    with forward slashes: Tcl treats backslashes as escape sequences and
    silently mangles Windows paths (measured: C:\\x\\y became one token)."""
    def fwd(p: str) -> str:
        return p.replace("\\", "/")

    for b in blocks:
        os.makedirs(b["outdir"], exist_ok=True)  # Vivado will not create these
    body = "".join(BLOCK_TCL.format(top=b["top"], src=fwd(b["src"]),
                                    out=fwd(b["outdir"]),
                                    xdc=fwd(xdc)) for b in blocks)
    with open(tcl_path, "w", encoding="utf-8") as f:
        f.write(TCL_TEMPLATE.format(part=part, blocks=body))
    return tcl_path


def parse_timing(text: str) -> dict:
    """Design Timing Summary -> {wns_ns, tns_ns, whs_ns}. Vivado prints the
    values on a later row than the header, columns aligned by 2+ spaces, so
    parsing is positional: the header token's column index selects the value
    from the first subsequent numeric row (measured against 2026.1 report
    text, not assumed). All-UNKNOWN when absent."""
    lines = text.splitlines()

    def column(header_token: str):
        for i, line in enumerate(lines):
            if header_token in line:
                # Pipes are layout, not columns: drop them so pipe tables
                # and space-aligned tables index identically.
                toks = [t for t in
                        re.split(r"\s{2,}", line.replace("|", " ").strip())
                        if t]
                idx = next((n for n, t in enumerate(toks)
                            if header_token in t), None)
                if idx is None:
                    continue
                for follow in lines[i + 1:i + 6]:
                    # Ints AND floats: integer endpoint counts occupy
                    # columns too — skipping them shifts every index right
                    # of them (measured: WHS read as WPWS).
                    vals = [float(x) for x in
                            re.findall(r"-?\d+(?:\.\d+)?", follow)]
                    if len(vals) > idx:
                        return vals[idx]
        return None

    wns = column("WNS(ns)")
    if wns is None:
        m = re.search(r"Worst Negative Slack.*?(-?[\d.]+)\s*ns", text)
        wns = float(m.group(1)) if m else None
    return {
        "wns_ns": wns,
        "tns_ns": column("TNS(ns)"),
        "whs_ns": column("WHS(ns)"),
    }


def parse_util(text: str) -> dict:
    """Slice Logic summary -> {lut, ff, bram, dsp} (None when absent).
    Tolerant of Vivado's `*` footnote markers and column drift (measured
    against 2026.1 report text, not assumed)."""
    def num(label):
        m = re.search(r"\|\s*" + label + r"\*?\s*\|\s*(\d+)", text)
        return int(m.group(1)) if m else None

    return {"lut": num("Slice LUTs"), "ff": num("Slice Registers"),
            "bram": num("Block RAM Tile"), "dsp": num("DSPs?")}


def parse_drc(text: str) -> dict:
    """DRC report -> {violations: int|None, clean: bool|None}."""
    if not text.strip():
        return {"violations": None, "clean": None}  # no report, no claim
    if re.search(r"No DRC violations were found", text):
        return {"violations": 0, "clean": True}
    m = re.search(r"(\d+)\s+(?:Critical warnings|violations?)\s+\(DRC", text,
                  re.IGNORECASE)
    if m:
        return {"violations": int(m.group(1)), "clean": False}
    crit = len(re.findall(r"CRITICAL WARNING.*DRC", text))
    return {"violations": crit if crit else None, "clean": crit == 0}


def vivado_version() -> str:
    try:
        p = subprocess.run(
            [VIVADO_BAT, "-mode", "batch", "-notrace", "-source",
             os.path.join(os.path.dirname(os.path.abspath(__file__)),
                          "sim", "viv_ver.tcl")],
            capture_output=True, text=True, timeout=300)
        m = re.search(r"Vivado v([\d.]+)", (p.stdout or "") + (p.stderr or ""))
        return m.group(1) if m else ""
    except (OSError, subprocess.SubprocessError):
        return ""


def run_block(top: str, src: str, outdir: str, tcl_path: str,
              timeout_s: int = SYNTH_TIMEOUT_S) -> VivadoRun:
    """Availability + version probe for one block (the batch tcl itself is
    executed once for all blocks via execute_batch). Never raises."""
    run = VivadoRun()
    os.makedirs(outdir, exist_ok=True)
    if not os.path.isfile(VIVADO_BAT):
        run.status, run.reason = "UNAVAILABLE", "vivado.bat not found"
        run.limitations.append(note(
            "no Vivado install at the expected path",
            "use the open-source flow (Yosys synth) or install Vivado"))
        return run
    run.tool_version = vivado_version()
    if not run.tool_version:
        run.status, run.reason = "UNAVAILABLE", "vivado not responding"
    return run


def execute_batch(tcl_path: str, workdir: str,
                  timeout_s: int = SYNTH_TIMEOUT_S) -> tuple[int, str, float]:
    """Run the whole batch tcl once (amortizes Vivado startup over blocks).
    Returns (rc, log, seconds). Timeout -> (-1, log, seconds) for the caller
    to disposition as UNPROVEN, never as PASS."""
    os.makedirs(workdir, exist_ok=True)
    start = time.perf_counter()
    try:
        p = subprocess.run(
            [VIVADO_BAT, "-mode", "batch", "-notrace",
             "-log", os.path.join(workdir, "batch.log"),
             "-journal", os.path.join(workdir, "batch.jou"),
             "-source", tcl_path],
            capture_output=True, text=True, timeout=timeout_s)
        dur = time.perf_counter() - start
        return p.returncode, (p.stdout or "") + (p.stderr or ""), dur
    except subprocess.TimeoutExpired as exc:
        dur = time.perf_counter() - start
        partial = ""
        if exc.stdout:
            partial += exc.stdout.decode(errors="replace") \
                if isinstance(exc.stdout, bytes) else exc.stdout
        return -1, partial, dur
    except (OSError, subprocess.SubprocessError) as exc:
        return 127, f"UNAVAILABLE: {exc}", time.perf_counter() - start


def collect_block(outdir: str) -> dict:
    """Parse one block's reports. Missing/unparseable files -> UNKNOWN
    fields (printed + recorded), never invented numbers."""
    def read(name):
        try:
            with open(os.path.join(outdir, name), encoding="utf-8",
                      errors="replace") as f:
                return f.read()
        except OSError:
            return ""

    timing, util, drc = (read("timing.rpt"), read("util.rpt"),
                         read("drc.rpt"))
    routed = os.path.isfile(os.path.join(outdir, "post_route.dcp"))
    checks = {"synth": "PASS" if routed else "FAIL",
              "timing": parse_timing(timing), "util": parse_util(util),
              "drc": parse_drc(drc)}
    limitations = []
    if checks["timing"]["wns_ns"] is None:
        limitations.append(note(
            f"{outdir}: no timing numbers parsed (demo has no XDC/clocks)",
            "add an .xdc with create_clock + input/output delays, then "
            "re-run; until then timing is NOT verified"))
    if checks["util"]["lut"] is None:
        limitations.append(note(
            f"{outdir}: utilization table unparsed (report format drift?)",
            "open the util.rpt manually; the dcp still proves synthesis"))
    return {"checks": checks, "limitations": limitations}


def calculate_hashes(paths: list[str]) -> dict:
    out = {}
    for p in paths:
        try:
            h = hashlib.sha256()
            with open(p, "rb") as f:
                for chunk in iter(lambda: f.read(65536), b""):
                    h.update(chunk)
            out[p] = h.hexdigest()[:16]
        except OSError:
            continue
    return out


def normalize_evidence(run: VivadoRun) -> dict:
    return {
        "tool": "AMD Vivado", "tool_version": run.tool_version,
        "target_device": run.target_device, "rtl_commit": run.rtl_commit,
        "run_id": run.run_id,
        "requirement_ids": list(run.requirement_ids),
        "vivado": {"status": run.status, "checks": run.checks,
                   "duration_s": round(run.duration_s, 1),
                   "reason": run.reason},
        "artifacts": list(run.artifacts),
        "artifact_hashes": dict(run.artifact_hashes),
        "limitations": list(run.limitations),
        "evidence_hash": hashlib.sha256(
            json.dumps([run.tool_version, run.target_device, run.run_id,
                        run.status, run.checks], sort_keys=True,
                       default=str).encode()).hexdigest()[:16],
    }


def to_ledger(ledger, requirement_id: str, evidence: dict, artifact: str):
    """Vivado evidence -> ledger. Synth PASS with clean DRC ledger as PASS;
    anything else becomes explicit NOT_EXECUTED (never silent PASS). XSim is
    intentionally out of scope here (Verilator owns simulation)."""
    from evidence import EvidenceRecord
    v = evidence["vivado"]
    checks = {"synth": v["checks"].get("synth"),
              "drc": v["checks"].get("drc"),
              "timing_wns_ns": (v["checks"].get("timing") or {}).get("wns_ns"),
              "evidence_hash": evidence["evidence_hash"]}
    if v["status"] == "PASS" and v["checks"].get("synth") == "PASS" \
            and v["checks"].get("drc", {}).get("clean"):
        return ledger.append(EvidenceRecord(
            requirement_id, artifact, checks, "PASS",
            tool=evidence["tool"],
            tool_version=evidence["tool_version"], run_id=evidence["run_id"]))
    return ledger.record_not_executed(
        requirement_id, artifact,
        f"vivado {v['status']}: {v.get('reason', '')}",
        run_id=evidence["run_id"])


def report_status(run: VivadoRun) -> str:
    return (f"vivado {run.tool_version or '?'} [{run.target_device}]: "
            f"{run.status} ({run.duration_s:.0f}s)")
